[pytest]
;addopts = -vs -rf --html=./reports/report.html --self-contained-html --junitxml=./reports/report.xml
addopts = -vs -rf --clean-alluredir --alluredir=allure --screenshot=only-on-failure --video=retain-on-failure --full-page-screenshot
testpaths = tests

log_cli = 1
log_cli_level = DEBUG
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

base_url=https://www.rebrandly.com
